### ISSUE TITLE
Understanding the error messages

### ISSUE THREAD

**Issue by sainathadapa** [leeper/tabulizer#12]
Can you help me understand the following warnings and steps that I need to take to avoid them:
```R
extracted_data_all <- list_of_files %>% lapply(extract_tables, guess = TRUE, method = 'character')
# Fontconfig warning: "/etc/fonts/infinality/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
# Fontconfig warning: "/etc/fonts/infinality/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
# May 31, 2016 3:43:34 PM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont getawtFont
# INFO: Can't find the specified font Microsoft Sans Serif
# May 31, 2016 3:43:34 PM org.apache.fontbox.ttf.TrueTypeFont initializeTable
# SEVERE: An error occured when reading table name
# java.io.EOFException
# 	at java.io.RandomAccessFile.readUnsignedShort(RandomAccessFile.java:769)
# 	at org.apache.fontbox.ttf.RAFDataStream.readUnsignedShort(RAFDataStream.java:118)
# 	at org.apache.fontbox.ttf.NamingTable.initData(NamingTable.java:53)
# 	at org.apache.fontbox.ttf.TrueTypeFont.initializeTable(TrueTypeFont.java:280)
# 	at org.apache.fontbox.ttf.TrueTypeFont.getNaming(TrueTypeFont.java:114)
# 	at org.apache.fontbox.util.FontManager.analyzeTTF(FontManager.java:112)
# 	at org.apache.fontbox.util.FontManager.loadFonts(FontManager.java:75)
# 	at org.apache.fontbox.util.FontManager.findTTFontname(FontManager.java:290)
# 	at org.apache.fontbox.util.FontManager.findTTFont(FontManager.java:326)
# 	at org.apache.pdfbox.pdmodel.font.PDTrueTypeFont.getExternalFontFile2(PDTrueTypeFont.java:584)
# 	at org.apache.pdfbox.pdmodel.font.PDTrueTypeFont.getawtFont(PDTrueTypeFont.java:510)
# 	at org.apache.pdfbox.pdmodel.font.PDSimpleFont.drawString(PDSimpleFont.java:110)
# 	at org.apache.pdfbox.pdfviewer.PageDrawer.processTextPosition(PageDrawer.java:260)
# 	at org.apache.pdfbox.util.PDFStreamEngine.processEncodedText(PDFStreamEngine.java:499)
# 	at org.apache.pdfbox.util.operator.ShowTextGlyph.process(ShowTextGlyph.java:62)
# 	at org.apache.pdfbox.util.PDFStreamEngine.processOperator(PDFStreamEngine.java:557)
# 	at org.apache.pdfbox.util.PDFStreamEngine.processSubStream(PDFStreamEngine.java:268)
# 	at org.apache.pdfbox.util.PDFStreamEngine.processSubStream(PDFStreamEngine.java:235)
# 	at org.apache.pdfbox.util.PDFStreamEngine.processStream(PDFStreamEngine.java:215)
# 	at org.apache.pdfbox.pdfviewer.PageDrawer.drawPage(PageDrawer.java:139)
# 	at org.apache.pdfbox.pdmodel.PDPage.convertToImage(PDPage.java:801)
# 	at technology.tabula.detectors.NurminenDetectionAlgorithm.detect(NurminenDetectionAlgorithm.java:93)
# 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
# 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
# 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
# 	at java.lang.reflect.Method.invoke(Method.java:606)
# 	at RJavaTools.invokeMethod(RJavaTools.java:386)
# 
# May 31, 2016 3:43:35 PM org.apache.fontbox.util.FontManager findTTFontname
# WARNING: Font not found: Microsoft Sans Serif
# May 31, 2016 3:43:35 PM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont getawtFont
# INFO: Can't find the specified font Microsoft Sans Serif,Italic
# May 31, 2016 3:43:35 PM org.apache.fontbox.util.FontManager findTTFontname
# WARNING: Font not found: Microsoft Sans Serif,Italic
# May 31, 2016 3:43:36 PM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont getawtFont
# INFO: Can't find the specified font Microsoft Sans Serif
# May 31, 2016 3:43:36 PM org.apache.fontbox.util.FontManager findTTFontname
# WARNING: Font not found: Microsoft Sans Serif
# May 31, 2016 3:43:37 PM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont getawtFont
# INFO: Can't find the specified font Microsoft Sans Serif
# May 31, 2016 3:43:37 PM org.apache.fontbox.util.FontManager findTTFontname
# WARNING: Font not found: Microsoft Sans Serif
# May 31, 2016 3:43:37 PM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont getawtFont
# INFO: Can't find the specified font Microsoft Sans Serif,Italic
# May 31, 2016 3:43:37 PM org.apache.fontbox.util.FontManager findTTFontname
# WARNING: Font not found: Microsoft Sans Serif,Italic
# May 31, 2016 3:43:38 PM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont getawtFont
# INFO: Can't find the specified font Microsoft Sans Serif
# May 31, 2016 3:43:38 PM org.apache.fontbox.util.FontManager findTTFontname
# WARNING: Font not found: Microsoft Sans Serif
# May 31, 2016 3:43:41 PM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont getawtFont
# INFO: Can't find the specified font Microsoft Sans Serif
# May 31, 2016 3:43:41 PM org.apache.fontbox.util.FontManager findTTFontname
# WARNING: Font not found: Microsoft Sans Serif
# May 31, 2016 3:43:41 PM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont getawtFont
# INFO: Can't find the specified font Microsoft Sans Serif,Italic
# May 31, 2016 3:43:41 PM org.apache.fontbox.util.FontManager findTTFontname
# WARNING: Font not found: Microsoft Sans Serif,Italic
# May 31, 2016 3:43:42 PM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont getawtFont
# INFO: Can't find the specified font Microsoft Sans Serif,Italic
# May 31, 2016 3:43:42 PM org.apache.fontbox.util.FontManager findTTFontname
# WARNING: Font not found: Microsoft Sans Serif,Italic
# May 31, 2016 3:43:42 PM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont getawtFont
# INFO: Can't find the specified font Microsoft Sans Serif
# May 31, 2016 3:43:42 PM org.apache.fontbox.util.FontManager findTTFontname
# WARNING: Font not found: Microsoft Sans Serif
# May 31, 2016 3:43:42 PM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont getawtFont
# INFO: Can't find the specified font Microsoft Sans Serif
# May 31, 2016 3:43:42 PM org.apache.fontbox.util.FontManager findTTFontname
# WARNING: Font not found: Microsoft Sans Serif
```

Here is the session info
```R
sessionInfo()
# R version 3.3.0 (2016-05-03)
# Platform: x86_64-pc-linux-gnu (64-bit)
# Running under: Ubuntu 14.04.4 LTS
# 
# locale:
#  [1] LC_CTYPE=en_IN.UTF-8          LC_NUMERIC=C                  LC_TIME=en_IN.UTF-8          
#  [4] LC_COLLATE=en_IN.UTF-8        LC_MONETARY=en_IN.UTF-8       LC_MESSAGES=en_IN.UTF-8      
#  [7] LC_PAPER=en_IN.UTF-8          LC_NAME=en_IN.UTF-8           LC_ADDRESS=en_IN.UTF-8       
# [10] LC_TELEPHONE=en_IN.UTF-8      LC_MEASUREMENT=en_IN.UTF-8    LC_IDENTIFICATION=en_IN.UTF-8
# 
# attached base packages:
# [1] stats     graphics  grDevices utils     datasets  methods   base     
# 
# other attached packages:
# [1] data.table_1.9.6 magrittr_1.5     rlist_0.4.6.1    stringr_1.0.0    dplyr_0.4.3      tabulizer_0.1.14
# 
# loaded via a namespace (and not attached):
#  [1] tabulizerjars_0.1.2 R6_2.1.2            assertthat_0.1      parallel_3.3.0      DBI_0.4-1          
#  [6] tools_3.3.0         Rcpp_0.12.5         stringi_1.1.1       chron_2.3-47        rJava_0.9-8        
# [11] png_0.1-7  
```

**Comment by leeper** [comment]
Thanks. Can you supply an example file and the output of a direct call to `extract_tables()` rather the `%>% lapply()` construction?

**Comment by sainathadapa** [comment]
The warnings don't go away when `%>% lapply` is not used. Sadly I can't supply an example pdf since it contains personal information. 
When the pdf file is viewed using the 'Document Viewer' in Ubuntu, the properties section says the following about the fonts:
```
This document contains non-embedded fonts that are not from the PDF Standard 1 4 fonts. If the substitute fonts selected by fontconfig are not the same as the fonts used to create the PDF, the rendering may not be correct.
```
Are the warnings because of this (probably)?

**Comment by leeper** [comment]
Does `extract_text()` work on the file to return a character vector? If not, I suspect there might not be anything that can be done. If it works, there's probably some hope and I can investigate further.
